# permissions for end users to view ecrsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ecrsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ecr-secret-operator
    app.kubernetes.io/part-of: ecr-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: ecrsecret-viewer-role
rules:
- apiGroups:
  - secrets.fireflycons.io
  resources:
  - ecrsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.fireflycons.io
  resources:
  - ecrsecrets/status
  verbs:
  - get
