#!/usr/bin/env bash
#
# Helmchart postprocessor. Fills gaps left by kustohelmize

CHART_DIR=$1
LOCALBIN=$2

echo "Postprocessing chart in $CHART_DIR"

# Remove namespace declarations
rm $CHART_DIR/templates/*namespace*.yaml
for f in $(ls $CHART_DIR/templates/*.yaml)
do
    sed -i -s '/^  namespace:/d' $f;
done

# Patch rolebinding subject nameapace
for f in $(ls $CHART_DIR/templates/*binding*.yaml) ; do
    sed -i -s 's/^  - namespace:.*/  - namespace: {{ .Release.Namespace }}/' $f;
    sed -i -s 's/^    namespace:.*/    namespace: {{ .Release.Namespace }}/' $f;
done

# Make Prometheus service monitor conditonal
TEMPLATE=$CHART_DIR/templates/ecr-secret-operator-controller-manager-metrics-monitor-servicemonitor.yaml

sed -i '1 i\{{- if .Values.prometheus.enabled }}' $TEMPLATE
sed -i '$ a\{{- end}}' $TEMPLATE

# Clean values.yaml
$LOCALBIN/yq -i e 'del(.. | select(tag == "!!map" and length == 0))' $CHART_DIR/values.yaml 
